awaescher/OllamaSharp

OllamaApiConsole/Program.cs
src/IOllamaApiClient.cs
src/OllamaApiClient.cs

Implement IsRunning() as health checks

---

.gitignore
README.md
src/IOllamaApiClient.cs
src/OllamaApiClient.cs
src/OllamaApiClientExtensions.cs
src/OllamaSharp.csproj
test/OllamaApiClientTests.cs
test/TestOllamaApiClient.cs

Implemented a new syntax leveraging `IAsyncEnumerable` to let users choose between callbacks and stream enumerations.
The new calls allowing for `IAsyncEnumerable` instead of an action callback are:
```csharp
IAsyncEnumerable<CreateStatus?> CreateModel(CreateModelRequest request, [EnumeratorCancellation] CancellationToken cancellationToken = default);
IAsyncEnumerable<PullStatus?> PullModel(PullModelRequest request, [EnumeratorCancellation] CancellationToken cancellationToken = default);
IAsyncEnumerable<PushStatus?> PushModel(PushRequest request, [EnumeratorCancellation] CancellationToken cancellationToken = default);
IAsyncEnumerable<ChatResponseStream?> StreamChat(ChatRequest chatRequest, [EnumeratorCancellation] CancellationToken cancellationToken = default) …
```

Added IAsyncEnumerable implementations for various API calls

---

OllamaSharp.sln
src/IOllamaApiClient.cs
src/Models/Chat/ChatResponse.cs
src/OllamaApiClient.cs
test/OllamaApiClientTests.cs
test/TestOllamaApiClient.cs

When implementing Ollama Connector in Semantic Kernel was evident that lack of support for providing metadata when using the non-streaming chat endpoint as well as the different behavior of the Chat endpoint returning a list of messages including the original chathistory, different from the format received from the underlying API.
This change introduces the `Chat` method following the name `StreamChat` for non-streaming requests.

Add Chat With Metadata Endpoint to OllamaSharp client

---

OllamaApiConsole/Demos/ToolConsole.cs
src/Models/Chat/MessageBuilder.cs
test/ChatTests.cs
test/OllamaApiClientTests.cs

I just tried out the **tool chat console demo** and received the following error:
`The JSON value could not be converted to System.String. Path: $.message.tool_calls[[0]].function.arguments.fahrenheit | LineNumber: 0 | BytePositionInLine: 203.`
I noticed that the "required"-field in the function definition seemed off, since it was set to "fahrenheit".
According to the [function calling API documentation of OpenAPI ](https://platform.openai.com/docs/guides/function-calling/step-2-describe-your-function-to-the-model-so-it-knows-how-to-call-it) this should be a property name, which is why I changed it to "format" instead.
I also noticed that the tool call is ignored since the MessageBuilders "HasValue" function ignores the ToolCalls and changed it accordingly.
I am not sure whether the Image …

Fix tool chat console demo

---

src/OllamaApiClient.cs

The default C# serializer will serialize strings containing an apostrophe as \u0027 as some deserializers don't handle this correctly which can lead to escaping the containing string and causing security issues. Ollama however handles this correctly but the conversion from apostrophe to unicode code is not undone when deserialized. This leads to the prompts containing literal unicode codes instead of the intended character which can cause odd behavior from models.
Since the Ollama deserializer handles the apostrophes correctly we can use the `UnsafeRelaxedJsonEscaping` encoder to tell the serializer to not use this behavior and resolve this.

Add serializer options to fix #68

---

README.md
src/HttpRequestMessageExtensions.cs
src/IOllamaApiClient.cs
src/Models/Chat/ChatRequest.cs
src/Models/CopyModel.cs
src/Models/CreateModel.cs
src/Models/DeleteModel.cs
src/Models/Embed.cs
src/Models/Generate.cs
src/Models/OllamaRequest.cs
src/Models/PullModel.cs
src/Models/PushModel.cs
src/Models/ShowModel.cs
src/OllamaApiClient.cs
src/OllamaApiClientExtensions.cs
test/OllamaApiClientTests.cs
test/TestOllamaApiClient.cs

Adds the possibilities to ... 
- ... add custom http request headers to requests
- ... define default http request headers to the `OllamaApiClient` that will be sent with every request

Allow custom http request headers

---

.github/workflows/ci.yml

The current action trigger builds new versions for changes on any file. This is not necessary, we need to filter on changes within the `/src` folder.

Only build new versions on source code changes

---

src/Models/Chat/ChatRequest.cs
src/Models/Chat/Message.cs
test/OllamaApiClientTests.cs

All requests sent to chat endpoint were sending `tools`, `tool_calls` and `images` when not being necessary in the server-side, this prevents extra information being sent to the server.

Removing extra info from request when not needed

---

src/Models/Chat/Converter/StringDictionaryConverter.cs
src/Models/Chat/Message.cs
test/ChatTests.cs
test/OllamaApiClientTests.cs

Temporaty fix (Non-breaking) to support parameters values that aren't strings from the Ollama API.
Ideally the Dictionary should support <string, object?> but this is coming soon as a breaking change, this PR changes it to not break for now, before the shift happens.

Support different types returned for arguments

---

demo/Demos/ImageChatConsole.cs
demo/OllamaApiConsole.csproj
src/ByteArrayExtensions.cs
src/Chat.cs
src/MicrosoftAi/AbstractionMapper.cs
src/OllamaApiClient.cs
test/AbstractionMapperTests.cs
test/ChatTests.cs
test/OllamaApiClientTests.cs

- Enabled the use of byte array images with Microsoft.Extensions.AI
- Add missing top_k and modelId for Microsoft.Extensions.AI
- Fixed [CVE-2024-41131](https://github.com/advisories/GHSA-63p8-c4ww-9cg7)
- Improved handling of `OllamaApiClient.Dispose()`

Merge improved image handling

---

demo/OllamaApiConsole.csproj
src/MicrosoftAi/AbstractionMapper.cs
src/MicrosoftAi/OllamaFunctionResultContent.cs
src/OllamaApiClient.cs
src/OllamaSharp.csproj
test/AbstractionMapperTests.cs
test/ChatTests.cs
test/OllamaApiClientTests.cs
test/Tests.csproj

- Currently the implementation is ignoring sending functions results back to the model with the `Message.Tool` Role, this implementation adds this behavior for `AI Abstractions Mapping`
- Warnings fixes
- Not sending tool_calls or images when not provided.

Add message tool support for AI Abstractions

---

src/MicrosoftAi/AbstractionMapper.cs
test/AbstractionMapperTests.cs

This PR adds a specific condition that will prevent generating extra messages when the abstraction only have `FunctionResultContent` Contents.
Also fixes a limitation where `stop sequences` implementation was expecting a `string[]` not working even when a valid `IEnumerable<string>` was provided.

Fix: Avoid generating empty tool messages when there's no content for it

---

src/OllamaApiClient.cs
test/OllamaApiClientTests.cs

- When attempting to use function calling with streaming, the backend API does not fail which leaves the client to think it was successful as a supported scenario.
This change ensures that any attempt of using the streaming API with tools fails before sending the request to the server.
As soon we have this limitation removed from Ollama, we can revert this change.

Add exception for not supported streaming tools scenario

---

src/Models/JsonSchema.cs

https://github.com/awaescher/OllamaSharp/issues/153

Improve JsonSchema.ToJsonSchema

---

src/Chat.cs
test/Tests.v3.ncrunchproject

#159 added a `format` argument to the `Chat` class. However, it broke the overload resolution so that in certain overloads, the new `format` argument was wrongly assigned to the `CancellationToken`. This was pretty hard to debug, due to a serialization error message. To prevent this, I added the check to throw a specialized exception in addition to fixing the overloads.

Fix SendAsync/SendAsAsync overloads introduced in #159

---

src/OllamaApiClient.cs

This means that when putting the client in a field/property, you don't have to write code like:
```cs
((IDisposable)Client)?.Dispose();
```
Instead you can just write:
```cs
Client?.Dispose();
```

Publicly expose OllamaApiClient.Dispose

---

src/Models/Chat/Message.cs

https://github.com/ollama/ollama/commit/5f8051180e3b9aeafc153f6b5056e7358a939c88

Add Index for ToolCall Function

---

.github/workflows/ci.yml
Directory.Build.targets
OllamaSharp.sln
demo/OllamaApiConsole.csproj
src/MicrosoftAi/AbstractionMapper.cs
src/Models/JsonSchema.cs
src/OllamaApiClient.cs
src/OllamaSharp.csproj
test/FunctionalTests/ChatTests.cs
test/FunctionalTests/OllamaApiClientTests.cs
test/TestOllamaApiClient.cs
test/Tests.csproj

This pull request:
- Adds `netstandard2.1`, `.net8.0`, `net9.0` targets, which may improve performance at a small cost to the size of the `nupkg`.
- Upgrades NuGet packages to the latest versions.
I also noticed this library is using NUnit, which is a little old and verbose. Would you be interested in migrating to [xUnit](https://github.com/xunit/xunit) (or [TUnit](https://github.com/thomhurst/TUnit)), or are you okay sticking with NUnit?

Upgrade target frameworks and packages

---

.github/workflows/docs.yml

When #162 was merged, it added .NET 9 to the library, but the documentation workflow was not updated to also utilize .NET 9. This has caused all documentation builds to fail since.
This change adds appropriate .NET version to the workflow file.

Corrected documentation build after #162 added .NET 9

---

src/Chat.cs
src/Constants/Application.cs
src/MicrosoftAi/AbstractionMapper.cs
src/Models/Chat/ChatDoneResponseStream.cs
src/Models/CopyModel.cs
src/Models/CreateModel.cs
src/Models/DeleteModel.cs
src/Models/Embed.cs
src/Models/Generate.cs
src/Models/ListModels.cs
src/Models/ListRunningModels.cs
src/Models/OllamaOption.cs
src/Models/PullModel.cs
src/Models/PushModel.cs
src/Models/RequestOptions.cs
src/Models/ShowModel.cs

#166 ended up moving a large chunk of the `JsonPropertyNames` over to constants while I was finding and combing other magic strings in the `OllamaApiClient`. This moves the rest of the strings in the model classes over to the constants to keep everything consistent.

Moved the rest of the model JsonPropertyNames to constants for consistency

---

src/Constants/Application.cs
src/MicrosoftAi/AbstractionMapper.cs
src/Models/OllamaOption.cs
test/AbstractionMapperTests.cs

Hey, thanks a lot for creating this project! I think I found a bug related to missing MaxOutputTokens field mapping, I fixed it both in the code and in the unit test.
I think i found another one but it's within `Semantic Kernel connector` library. The `OllamaPromptExecutionSettings` doesn't contain and thus you cannot send max output tokens, I will try to report it them
```csharp
[JsonPropertyName("num_predict")]
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
public double? NumPredict
{
get => this._numPredict;
set
{
this.ThrowIfFrozen();
this._numPredict = value;
}
}
```

fixed no max output tokens

---

src/OllamaSharp/Chat.cs
src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs
src/OllamaSharp/MicrosoftAi/ChatResponseUpdateAppender.cs
src/OllamaSharp/MicrosoftAi/ChatResponseUpdateBuilder.cs
src/OllamaSharp/MicrosoftAi/IAsyncEnumerableExtensions.cs
src/OllamaSharp/Models/Chat/MessageBuilder.cs
src/OllamaSharp/OllamaApiClient.cs
src/OllamaSharp/OllamaSharp.csproj
src/SourceGenerators/OllamaToolGenerator.cs
test/AbstractionMapperTests.cs
test/Tests.csproj

Fix warnings

---

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs

GetResponseAsync was already accounting for tool calls, I'm reusing the same logic for streaming.
@awaescher any ideas on how can we add a test for this?
Contributes to https://github.com/dotnet/extensions/issues/5975.

Account for ToolCalls on GetStreamingResponseAsync

---

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs
src/OllamaSharp/Models/Embed.cs
test/AbstractionMapperTests.cs

I've added `keep_alive` to `ChatOptions`. It was already supported in `EmbeddingGenerationOptions`. 
Additionaly I've changed from long to string value of `keep_alive` in `EmbeddingGenerationOptions` to be consistent with Ollama API doc.

Support for keep_alive in MicrosoftAi ChatOptions

---

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs
test/AbstractionMapperTests.cs

Recent versions of Microsoft.Extensions.AI have removed certain on-by-default transformations in its JSON schema generation capabilities which were meant to cater to OpenAI restrictions around JSON schema. This PR reinstates the original schema generation behaviour by applying a "schema transformer" on the individual IChatClient implementation.

Add a schema transformer to the IChatClient implementation.

---

src/OllamaSharp/OllamaSharp.csproj

According to the [package documentation](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/9.0.5#readme-body-tab):
> This library is not necessary nor recommended when targeting versions of
> .NET that include the relevant support.
According to [Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1), `IAsyncEnumerable<T>` is included in .NET Core 3 and .NET Standard 2.1. So this package is only needed for .NET Standard 2.0.

Only reference package Microsoft.Bcl.AsyncInterfaces when required.

---

Directory.Packages.props
src/OllamaSharp.ModelContextProtocol/McpClientOptions.cs
src/OllamaSharp.ModelContextProtocol/Tools.cs
tests/OllamaSharp.ModelContextProtocol.Tests/Infrastructure/TestClientTransport.cs
tests/OllamaSharp.ModelContextProtocol.Tests/Infrastructure/TestTransport.cs

Updates ModelContextProtocol Nuget package to version 0.2.0-preview.3. Tests that I could run without a locally running instance of Ollama or the testing model all passed. No changes to any code except for updating Using statements and fixing a type name conflict. Projects running MCP Nuget version 0.2.0 or higher will experience errors when using OllamaSharp.ModelContextProtocol because of breaking changes.

Updates ModelContextProtocol Nuget to version 0.2.0-preview.3

---

src/SourceGenerators/ToolSourceGenerator.cs
test/FunctionalTests/OllamaApiClientTests.cs

For `Allows_Line_Breaks_In_Summary`, the new lines were ending up in an unescaped strings. So I replace the newlines with spaces to make the test pass.
For `ListRunningModels`, there was race condition. The call to `GenerateAsync` and `ListRunningModelsAsync` were running at the same time, so usually the call to `ListRunningModelsAsync` returned no running models the first time the test was run. When the test was run a second time, the model would already be running and the test would pass. I fixed this by ensure that the call to `GenerateAsync` completes before calling `ListRunningModelsAsync`. While I was at it, I made the prompt generate a smaller number of tokens so the test completes faster.

Fix tests Allows_Line_Breaks_In_Summary and ListRunningModels.

---

Directory.Packages.props

Updating packages to latest Microsoft Extensions AI 9.9.0
> [!NOTE]
> I noticed some pontentially unrelated issues running the `Allows_Line_Breaks_In_Summary` UnitTest which seems related to Windows environment.
> 
> Pointing out to the `GenerateToolClassCode`, when it escapes `methodSummary` it does not work for the `\r` breaks and gives a compilation error.
Just realized there's a PR attemping to address the issue already in the queue.
- #309

Update ME.AI packages to 9.9.0

---

src/OllamaSharp.ModelContextProtocol/Server/McpClientTool.cs

When Invoking an McpMcpServerTool function, it the underlining method throws an exception, the ToolInvoker simply returns null, this often causes the model to allucinate, thinking that the function executed correctly.
Error responses from CallToolAsync now return the error content prefixed with 'Error:' instead of null, providing more informative feedback to callers.
I'm not sure wether simply prefixing "Error" to the result is the best way to go about doing this, but at least the content in the CallToolResponse.Content is not lost.
We could instead add an IsError property to the ToolResult class and handle it differently in Chat.cs (i.e. new Message(ChatRole.Tool, "Tool: .. Error:...")) but I think that would be a more invasive change and probably would require changes to the …

Forwarding Error content in McpClientTool

---

src/OllamaSharp/Models/JsonSourceGenerationContext.cs
src/OllamaSharp/OllamaApiClient.cs

Currently, OllamaSharp encounters compatibility issues with System.Text.Json's reflection-based serialization when compiled with NativeAOT.
This PR refactors the JSON serialization and deserialization in the project to use source-generation mode. The primary goal is to enable full compatibility with NativeAOT

Use source-generation JSON for NativeAOT support
