awaescher/OllamaSharp

src/Models/GenerateEmbedding.cs, test/OllamaApiClientTests.cs
=> Fix property name 'embedding'

src/Chat.cs, src/Models/Chat/ChatRequest.cs, src/Models/Chat/Message.cs, src/OllamaApiClient.cs, test/OllamaApiClientTests.cs, test/TestOllamaApiClient.cs
- Changed the Messages from a IEnumerable to a IList
- Gave the Message class ctors for all plausable use cases -> Also added one for json deserialization
- Changed the tests according to the new changes, and more stuff to be more readable
Fixes:
- https://github.com/awaescher/OllamaSharp/issues/11
- https://github.com/awaescher/OllamaSharp/issues/9
=> Implements Github Issues 11 & 09

src/Diagnostics/IsExternalInit.cs, src/OllamaApiClient.cs, src/OllamaSharp.csproj
=> Change TargetFramework to netstandard2.0

src/Chat.cs
Hello there 🙋
recently I was developing a chat bot application using OllamaSharp and I was missing an api to set the current message history.
The existing way by automatically adding to the message history through the `SendAs` method does not work for my case
=> Added api to set the message history

OllamaApiConsole/Demos/ToolConsole.cs
As discussed in #70, I would like to add a simple tool function execution example to the tool console demo to demonstrate how the LLM acts upon tool responses.
=> Add tool function execution demo

src/OllamaApiClient.cs
=> Added IncomingJsonSerializerOptions on OllamaApiClient

src/OllamaApiClient.cs
=> chore: update OllamaApiClient.cs

src/Models/Chat/ChatRequest.cs, src/Models/Chat/ChatResponseStream.cs, src/Models/Chat/ChatRole.cs, src/Models/Chat/Converter/ChatRoleConverter.cs, src/Models/Chat/Message.cs, src/Models/Exceptions/ModelDoesNotSupportToolsException.cs, src/Models/Exceptions/OllamaException.cs, src/Models/ListModels.cs, src/Models/OllamaRequest.cs, src/Models/PullModel.cs, src/Models/PushModel.cs, src/Models/ShowModel.cs, src/OllamaApiClient.cs, src/OllamaApiClientExtensions.cs, src/OllamaSharp.csproj
=> Add xml documentation

src/OllamaApiClient.cs
=> remove ConversationContextWithResponse

src/MicrosoftAi/AbstractionMapper.cs, test/AbstractionMapperTests.cs, test/OllamaApiClientTests.cs
- TopK is a missing parameter in the mapping for AI Abstractions.
- As part of this PR I'm fixing this small bug and adding a UT to ensure all parameters are passed to the request.
=> Add missing TopK + UT for AI Abstractions CompleteAsync

demo/Demos/ImageChatConsole.cs, src/ByteArrayExtensions.cs, src/Chat.cs, src/MicrosoftAi/AbstractionMapper.cs, test/AbstractionMapperTests.cs, test/ChatTests.cs
=> Fix byte array handling for microsoft image abstractions

demo/OllamaApiConsole.csproj
=> Update to ImageSharp 3.1.5 explicitly

demo/Demos/ToolConsole.cs, src/MicrosoftAi/AbstractionMapper.cs, src/Models/Chat/ChatRequest.cs, test/OllamaApiClientTests.cs
=> Rename Properties to Property

src/Chat.cs, src/Models/Chat/ChatRequest.cs, src/Models/Generate.cs
Fixes #155.
Ideally these functions could be cleaned up as well so you don't have to pass the tools argument, will leave that to the maintainer's discretion.
=> Add support for Json Schema in Chat

src/MicrosoftAi/AbstractionMapper.cs, test/AbstractionMapperTests.cs
This PR adds support for using the Structured Output with the Microsoft.Extensions.AI abstractions.
=> Added support for structured output when using Microsoft.Extensions.AI

Directory.Packages.props, demo/OllamaApiConsole.csproj, src/OllamaSharp.ModelContextProtocol/OllamaSharp.ModelContextProtocol.csproj, src/OllamaSharp/OllamaSharp.csproj, src/SourceGenerators/OllamaSharp.SourceGenerators.csproj, test/Tests.csproj, tests/OllamaSharp.ModelContextProtocol.Tests/OllamaSharp.ModelContextProtocol.Tests.csproj
Use a central package management with `Directory.Packages.props`
=> Use central package management

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs, test/AbstractionMapperTests.cs
=> Add a test for the tool calls when streaming

src/OllamaSharp/Constants/Application.cs, src/OllamaSharp/Models/ShowModel.cs
https://github.com/ollama/ollama/releases/tag/v0.6.4
https://github.com/ollama/ollama/commit/e172f095ba4af2c98d7744ce4ffcf4cd3a8e123c#diff-9eddf4dc51bf6a0125ca7fb094468ad284112270385c41cebce4f8f0a29620ab
=> Add ShowModelResponse.Capabilities

src/OllamaSharp/IOllamaApiClient.cs, src/OllamaSharp/OllamaApiClient.cs, test/OllamaApiClientTests.cs, test/TestOllamaApiClient.cs
=> Return version as string

Directory.Packages.props
=> Bump versions of Microsoft.Extensions.AI and ModelContextProtocol

src/OllamaSharp/Chat.cs, src/OllamaSharp/Models/Chat/ChatRequest.cs
Allow controlling `Think` when using the `Chat` class
=> Support think with Chat

src/OllamaSharp/Chat.cs, src/OllamaSharp/Models/Chat/ChatRequest.cs
https://github.com/ollama/ollama/blob/aaa7818000c42a82fc030212c35ef83f9799efd7/api/types.go#L89
=> Update Chat.Think to Nullable, Used for set null to do not parse <Think>.

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs
This plumbs through the token usage when using Microsoft.Extensions.AI and the streaming api. Without this, the ChatDoneResponseStream packet just gets coalesced to an empty text update.
=> Add token usage to last value produced by IChatClient.GetStreamingResponseAsync

Directory.Packages.props, demo/Demos/ExtensionsAiConsole.cs, demo/OllamaApiConsole.csproj, demo/OllamaConsole.cs, demo/Program.cs, src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs, src/OllamaSharp/MicrosoftAi/ChatOptionsExtensions.cs, test/AbstractionMapperTests.cs
Add new demo console for usage with Extensions.AI
=> Add Extensions.AI demo

src/OllamaSharp/Models/Chat/Message.cs
https://github.com/ollama/ollama/blob/main/docs/api.md?plain=1#L503
https://github.com/ollama/ollama/blob/main/docs/api.md?plain=1#L906
https://github.com/ollama/ollama/releases/tag/v0.9.6
=> Add Message.ToolName

src/OllamaSharp/Constants/Application.cs, src/OllamaSharp/Models/ListRunningModels.cs
https://github.com/ollama/ollama/releases/tag/v0.10.0
=> Add ListRunningModelsResponse.ContextLength

src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs
Refactor `ToChatResponseUpdate` to streamline content handling and improve readability. Now tool calls content does not get left out when using gpt-oss model.
Fix for #305
=> Fix for #305

demo/OllamaConsole.cs, src/OllamaSharp/Chat.cs, src/OllamaSharp/MicrosoftAi/AbstractionMapper.cs, src/OllamaSharp/Models/Chat/ChatRequest.cs, test/AbstractionMapperTests.cs
#312
Implementation of enhancement #312 GPT-OSS (and other string based) think mode
=> Implementation of enhancement #312 GPT-OSS
